### ISSUE TITLE
Where can I get demo hardware

### ISSUE THREAD

**Issue by FingerLiu** [ShapeLab/SwarmUI#1]
Really interesting , and I am wondering where can I get the hardware...

**Comment by paulscott56** [comment]
The files for the PCB and 3d printed bits seem to be included in the repo. You should not have an issue with getting them made very cheaply.

**Comment by ju-Skinner** [comment]
thanks Paul

**Comment by TomasLang** [comment]
Hey
Intreating, can I buy 30-100?
Please, wtitten me to e-mail dimon.chudakov@gmail.com

**Comment by Retia-development** [comment]
Problably not the best question, but any suggestions where i can manufacture those cheap for low volume(1-100), i live in the EU and overall manufacturing pcb's is quite cost heavy (as much as 7 dollars per pcb) which is to much for me.
Or even better where i can order an complete DiY kit since that means i don't have to think about the engines etc anymore.

**Comment by TomasLang** [comment]
I need 30-100 finished with the program. I plan to use in children's entertainment
to start

**Comment by paulscott56** [comment]
You can order pcb's via https://oshpark.com Their prices are generally very good I find

**Comment by TomasLang** [comment]
Thanks
But I find finished product - https://m.youtube.com/watch?v=ZVdAfDMP3m0

Paul, can you helm me?

**Comment by paulscott56** [comment]
Well, I guess with permission, I could do a manufacturing run of thousands and sell them on Tindie! Actually it is possible someone already is doing just that...

**Comment by Retia-development** [comment]
Out of curiousity, how would you manufacture them yourself paulscott56?

**Comment by TomasLang** [comment]
ейти на русский
I'm not having found where to buy.
ready to order 30-100 and offer partners
Paul, how much it will cost a little party?

**Comment by yazici** [comment]
I would love to buy many of these. I have been trying to do something similare with wemos d1 and motoshield, etc to teach my son programming with physical systems and one of my project ideas was a physical pacman... But i am a sw engineer and suck at mechanical stuff etc and could never build a small and durable robot like these... Using wemos, shields, and mechanical stuff, a single robot i make is about $20  . But since this is a single board and simpler networking could be cheaper of bulk manufavtured and sold... Any tips for having these made would be appreciated. Including pcb with components aleeady assembled, 3d print, motors etc. these doesnt look like i cand hand solder

**Comment by yazici** [comment]
Ps. Tindie doesnt have this

**Comment by xiaotianhu** [comment]
DLP LightCrafter is so expensive.Even I can make robots and receivers,I can't afford a DLP.Can I get something chipper instead?

**Comment by TomasLang** [comment]
Ready to order 30
I can pay $ 300.
I need:
1. 30 pieces
2. Easy to program management
Who can do?

**Comment by TomasLang** [comment]
these - https://m.youtube.com/watch?v=ZVdAfDMP3m0

**Comment by xerib59** [comment]
@TomasLang did you notice that you will also need the projector ? The price of this projector is something like 800$

**Comment by jgriffin1011** [comment]
I have the DLP, ready to purchase 10-30.

**Comment by TomasLang** [comment]
xerib59, Yes, I know that I need a projector :)

**Comment by xou822** [comment]
the pcb cost me 15 dollars for 10， but its hard to find some parts in china

**Comment by xou822** [comment]
and do you guys know what does the low voltage comparators do since it is in the bom but not in the schematics?
